version: '2'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-docker:/data/db
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql-docker:/var/log/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    depends_on:
      - redis
  redis:
    image: redis:3-alpine
    ports:
      - 6379:6379
  box:
    build: .
    command: python box.py
    volumes:
      - .:/app
