version: '2'
services:
  alpine:
    image: alpine
    command: ash
    tty: true
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-docker:/data/db
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql-docker:/var/log/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    depends_on:
      - redis
  redis:
    image: redis:3-alpine
    ports:
      - 6379:6379
  python:
    image: python:2.7-alpine
    command: python
    tty: true
  box:
    build: .
    command: python a.py
    ports:
      - 8000:8000
    volumes:
      - .:/app
